### ISSUE TITLE
Hero Text in Header area not following customized color selection

### ISSUE THREAD

**Issue by swanser** [godaddy/wp-velux-theme#64]
I have changed the color of all colors in the customize > colors > header section to a blue color. All of the settings: Site Title Text, Tagline Text, Hero Text, Hero Background all set to blue, yet only the main page's hero text in the header changes to the selected color. All other pages have a white color for the hero text.

**Comment by EvanHerman** [comment]
Hi @swanser 

It sounds like there is another plugin or snippet of CSS that is causing the override. I just did a test and the site title, tag line and hero background all remain consistent across multiple pages. I'm not seeing that white text issue that you are describing.

If you have a link to your site where the issue is occurring we can take a look.

Evan
